submiss/admin/views.py
from flask import render_template, request, Blueprint, redirect, url_for, flash, abort
from flask_login import current_user
from submiss import db
from submiss.models import (
    User,
    Submission,
    Notification,
    Announcement,
    Feedback,
)
from submiss.forms import ReviewForm, AnnounceForm, NotifForm,UserSubmissions
from datetime import datetime


admin = Blueprint("admin", __name__)


def admin_required(function):
    def wrapper(*args, **kwargs):
        if current_user.is_authenticated and current_user.user_type == "Admin":
            return function()
        else:
            return abort(403)

    wrapper.__name__ = function.__name__
    return wrapper


@admin.route("/admin_dash")
@admin_required
def admin_dash():
    return render_template("admin/admin_dash.html")


@admin.route("/review", methods=["GET", "POST"])
@admin_required
def review():
    form = ReviewForm()
    submissions = Submission.query.filter_by(correct=1).all()
    users = User.query.all()
    now = datetime.now()
    prev_submission=Submission.query.filter_by(correct=2).all()
    if form.validate_on_submit():
        submission = Submission.query.filter_by(id=form.submission_id.data).first()
        user = User.query.filter_by(id=submission.by).first()
        if form.review.data == "Accept":
            submission.correct = 2
            score=user.score+form.points.data
            submission.bug_id=form.bug_id.data
            message = (
                "Congratulations! Your Submission on "
                + submission.time.strftime("%d %b %Y at %I:%M %p")
                + " has been accepted on "
                + now.strftime("%d %b %Y at %I:%M %p")
                + ". You are given "
                + str(form.points.data)
                +" points, Which brings your total score to "
                +str(score)
            )
            user.update_score(form.points.data)
            user.upgrade_time = submission.time
        elif form.review.data=="Reject":
            submission.correct = 0
            message = (
                "Oops! Your Submission on"
                + submission.time.strftime("%d %b %Y at %I:%M %p")
                + " has not been accepted on "
                + now.strftime("%d %b %Y at %I:%M %p")
                + " .As it was not correct."
            )
        elif form.review.data=="AlreadySubmitted":
            submission.correct = 0
            message = (
                "Oops! Your Submission on"
                + submission.time.strftime("%d %b %Y at %I:%M %p")
                + " has not been accepted on "
                + now.strftime("%d %b %Y at %I:%M %p")
                + " .As it has been already been accepted before."
            )

        notification = Notification(uid=user.id, message=message)

        db.session.add(notification)

        db.session.commit()
        return redirect(url_for("admin.review"))
    return render_template(
        "admin/review.html", submissions=submissions, form=form, users=users, prev_submission=prev_submission
    )


@admin.route("/announce", methods=["GET", "POST"])
@admin_required
def announce():
    form = AnnounceForm()
    if form.validate_on_submit():
        announcement = Announcement(message=form.message.data)
        db.session.add(announcement)
        db.session.commit()
        flash("Announcement Sucessfull")
        return redirect(url_for("admin.announce"))
    return render_template("admin/announce.html", form=form)


@admin.route("/all_users")
@admin_required
def all_users():
    users = User.query.order_by(User.id.asc()).all()
    return render_template("admin/users.html", users=users)


@admin.route("/dnotif", methods=["GET", "POST"])
@admin_required
def dnotif():
    form = NotifForm()
    if form.validate_on_submit():
        notif = Notification(uid=form.uid.data, message=form.message.data)
        db.session.add(notif)
        db.session.commit()
        flash("Notification sent Sucessfully")
        return redirect(url_for("admin.dnotif"))
    return render_template("admin/dnotif.html", form=form)


@admin.route("/user_subs", methods=["GET", "POST"])
@admin_required
def user_subs():
    form=UserSubmissions()
    if form.validate_on_submit():
        submissions = Submission.query.filter_by(by=form.uid.data).order_by(Submission.time.desc()).all()
        user = User.query.filter_by(id=form.uid.data).first() 
        return render_template("admin/user_subs.html", submissions=submissions, user=user)
    return render_template('admin/usersearch.html',form=form)

@admin.route("/all_feeds")
@admin_required
def all_feeds():
    feedbacks = Feedback.query.order_by(Feedback.id.desc()).all()
    users = User.query.all()
    return render_template("admin/all_feeds.html", feedbacks=feedbacks, users=users)

submiss/templates/announcements.html
{% extends "base.html" %} {% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    width: 100%;
    min-height: 100vh;
  "
>
  <div class="container">
    {% for ancmt in ancmts %}
    <div class="card bg-white" style="margin-top: 2%">
      <div class="card-body" style="color:black; padding">{{ancmt.message}}</div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

submiss/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8" />
    {#
    <link
      rel="shortcut icon"
      href="{{ url_for('static', filename='img/favicon.ico') }}"
    />
    <meta property="og:title" content="Mothra" />
    <meta property="og:description" content="Home of Mothra." />
    <meta property="og:url" content="https://vmothra.fun" />
    <meta
      property="og:image"
      content="{{ url_for('static', filename='img/forwards.png') }}"
    />
    #}
    <title>Bug Bounty</title>
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css"
      integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l"
      crossorigin="anonymous"
    />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css"
    />
    <link rel="stylesheet" href="static/style.css" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </head>

  <body
    style="
      background-color: #000000;
      background-image: linear-gradient(315deg, #000000 0%, #000000 74%);
    "
  >
    <nav class="header">
      <div class="col-bug">
        <div class="BugNav">
          <img src="../static/icons8-bug-64.png" class="logo" />
          <a class="navbar-brand" href="{{url_for('index')}}">Bug Bounty</a>
        </div>
      </div>
      <div class="col-nav" id="navbar">
        <ul>
          <li>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('instructions')}}"
              ><span>Instructions</span></a
            >
          </li>
          <li>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('leaderboard')}}"
              ><span> Leaderboard</span></a
            >
          </li>
          {% if current_user.is_authenticated %}
          <li>
            <a
              style="width: 120px"
              class="anchorhover"
              href="{{url_for('announcements')}}"
              >Announcements</a
            >
          </li>
          <li>
            <a
          
              class="anchorhover"
              href="{{url_for('submissions')}}"
              >Submit answer</a
            >
          </li>
          {% if current_user.user_type=='Admin' %}
          <li>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('admin.admin_dash')}}"
              >Admin</a
            >
          </li>
          <li class="logout">
            <h5>{{ current_user.username }} {{current_user.score}}</h5>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('logout')}}"
              >Logout</a
            >
          </li>
          {% else %} {% if unread()>0 %}
          <li>
            <div class="blink_me">
              <a
                class="anchorhover"
                style="color: red; width: 115px"
                href="{{url_for('notifications')}}"
                >{{unread()}} Notifications</a
              >
            </div>
          </li>
          {% else %}
          <li>
            <a
              style="width: 115px"
              class="anchorhover"
              href="{{url_for('notifications')}}"
              >{{unread()}} Notifications</a
            >
          </li>
          {% endif %}
          <li class="logout">
            <h5>{{ current_user.username }} {{current_user.score}}</h5>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('logout')}}"
              >Logout</a
            >
          </li>
          {% endif %} {% else %}
          <li>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('login')}}"
              >Login</a
            >
          </li>
          <li>
            <a
              style="width: 100px"
              class="anchorhover"
              href="{{url_for('register')}}"
              >Register</a
            >
          </li>
          {% endif %}
        </ul>
      </div>
      <a
        href="javascript:void(0);"
        class="icon"
        style="margin-top: 27px"
        onclick="myFunction()"
      >
        <i class="fa fa-bars"></i>
      </a>
      <img
        src="static/pcc_logo.png"
        style="width: 75px; height: 75px; top: 0"
      />
    </nav>

    <div class="content text-white">
      <div class="container text-center">
        {% for mess in get_flashed_messages() %}
        <div
          class="alert alert-warning alert-dismissible fade show"
          role="alert"
        >
          {{ mess }}
          <button
            type="button"
            class="close"
            data-dismiss="alert"
            aria-label="Close"
          >
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
      </div>

      {% block content %} {% endblock %}
    </div>
    <!-- <footer class="footer text-center bg-dark pt-2">
        <span class="text-white">Bug Bounty.</p></span>
    </footer> -->
    <script
      src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
      integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
      integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
      integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF"
      crossorigin="anonymous"
    ></script>

    <script>
      var val = 0;
      function myFunction() {
        if (val % 2 == 0) {
          document.getElementById("navbar").style.display = "block";
          val++;
        } else {
          document.getElementById("navbar").style.display = "none";
          val++
        }
      }
      $(window)
        .on("load resize ", function () {
          var scrollWidth =
            $(".tbl-content").width() - $(".tbl-content table").width();
          $(".tbl-header").css({ "padding-right": scrollWidth });
        })
        .resize();
    </script>
  </body>
</html>

submiss/templates/feedback.html
{% extends "base.html" %} {% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    padding: 6%;
    width: 100%;
    min-height: 100vh;
    text-align: center;
    display: flex;
    justify-content: center;
    align-items: center;
  "
>
  <div class="feedcontainer">
    <h1 class="text-center" style="color: black;">Feedback</h1>
    <form method="POST" class="feedform">
      {{ form.hidden_tag() }}
      <div class="form-group">
        {{ form.feed.label(class="form-group text-dark text-center") }}
        {{form.feed(class='form-control bg-dark text-white', rows="10") }}<br />
      </div>
      <div class="form-group text-center">
        {{ form.submit(class="loginbtn") }}
      </div>
    </form>
  </div>
</div>

{% endblock %}

submiss/templates/home.html
{% extends "base.html" %} {% block content %} 
  <div class="bodystyle">
    <img src="static/test1.jpg" class="homeimg" alt="Ime Is Loaded">
    <div class="rightbody">
      <div class="right-text">
        <h2 class="BugBountyStyle">BugBounty</h2>
        </br>
        {%if current_user.is_authenticated%}
        <div class="container text-center">
        <div class="row" style="margin-top: 10%">
        <div class="col-sm" style="margin-top: 5%">
        <a
          href="{{ url_for('feedback') }}"
          class="btn1"
          role="button"
          aria-pressed="true"
          >Feedback</a
        >
      </div>
    </div>
    <div class="row" style="margin-top: 5%">
      <div class="col-sm" style="margin-top: 5%">
        <a
          href="#"
          class="btn1"
          role="button"
          aria-pressed="true"
          >Buggy Bus Website</a
        >
      </div>
        {%else%}
        <h3 style="color: orangered;
    font-family: monospace;">Please login/register first.</h3>
        {%endif%}
        </div>
      </div>
    </div>
  
    {% endblock %}
  </div>
  

submiss/templates/instructions.html
{% extends "base.html" %}
{% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    padding: 6%;
    width: 100%;
    min-height: 100vh;
  "
>
<div class="container">
  <h2 class="text-center">Instructions</h2>
  <div class="instruction" style="margin-top:5%">
    <h3>How to play : </h3>
    <h6><i> 1. Register yourself and a teammate first by clicking Register at homepage.</i></h6>
    <h6><i>2. If you want to participate alone you can register yourself also. Kindly give same roll numbers for both the members.</i></h6>
    <h6><i>3. Login at homepage and use your team name(case sensitive) and password given at the time of registration.</i></h6>
   
    <h6><i>4. Click on <B> BUGGY BUS WEBSITE </B> button to go to website in which you have find bugs and vulnerabilities.</i></h6>
    <h6><i>5. Take a screenshot of the bugs and vulnerabilities that you find and submit them in submit portal. For submissions related queries please read explanation given below.</i></p>
    <h6><i>6. If your submission is accepted then you will be given points accordingly for which you will be notified.</i></h6>
    <h6><i>Tip: Keep and eye out for announcements and notifications.</i></h6>
  </div>
  <div class="instruction" style="margin-top:5%">
    <h3>What bugs and vulnerabilities you can expect : </h3>
    <h6><i>1. There are many bugs such as Invalid link.</i></h6>
 
  </div>
  <div class="instruction" style="margin-top:5%">
    <h3>Submissions : </h3>
    <h6><i>1. In the main page you can submit your answers by clicking on 'Submit answer' button in the navigation bar.</i></h6>
    <h6><i>2. You have to submit screenshot of the bug/vulnerability along with the explanation why it is a bug/vulnerability.</i></h6>
    <h6><i>3. Try to keep your explanation simple.</i></h6>
   
    <h6><i>4. If the admin finds the explanation satisfactory then given points according to bugs/vulnerability that you have found. Otherwise you will get a rejected submission notification.</i></h6>
    <h6><i>5. You can expect the review of your submission within few hour of your submission. But for the submission given between <B> 11AM to 5PM </B>, the review will be done after 11.30AM only.</i></p>
  </div>

</div>
</div>
{% endblock %}

submiss/templates/lead_wait.html
{% extends "base.html" %}
{% block content %}

<h2 align="center" style="margin-top:20%">Login to see the Leaderboard.</h2>

{% endblock %}

submiss/templates/leaderboard.html
{% extends "base.html" %} {% block content %}
<div  style="background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    width: 100%;
    min-height: 100vh;">
<section class="leaderboard">
  <!--for demo wrap-->
  <div class="leadertable">
    <h1 style="color:black;">LeaderBoard</h1>
    <div class="leaderbox">
      <div class="tbl-header">
        <table cellpadding="0" cellspacing="0" border="0">
          <thead>
            <tr>
              <th  class="ColumnStyle">S.No</th>
              <th  class="ColumnStyle">Team Name</th>
              <th  class="ColumnStyle">Member1</th>
              <th  class="ColumnStyle">Member2</th>
              <th  class="ColumnStyle">Score</th>
            </tr>
          </thead>
        </table>
      </div>
      <div class="tbl-content">
        <table cellpadding="0" cellspacing="0" border="0">
          <tbody>
            {% set rank=namespace(value=1) %} {% for user in users %}
            <tr>
              <td class="RowStyle">{{rank.value}}</td>
              <td class="RowStyle">{{user.username}}</td>
              <td class="RowStyle">{{user.roll}}</td>
              {%if user.roll==user.roll2%}
              <td class="RowStyle">-</td>
              {%else %}
              <td class="RowStyle">{{user.roll2}}</td>
              {%endif %}
              <td class="RowStyle">{{user.score}}</td>
            </tr>
            {% set rank.value=rank.value+1 %} {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
</section>
</div>
{% endblock %}

submiss/templates/login.html
{% extends "base.html" %} {% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    padding: 6%;
    width: 100%;
    min-height: 100vh;
  "
>
  <div
    class="container"
    style="
      width: 300px;
      background: linear-gradient(
        #97d273 5%,

        rgba(109, 247, 194, 0.923) 100%
      );
      height: 60vh;
      box-shadow: 3px 3px 15px #181717;
      border-radius: 5px;
    "
  >
    <div class="text-center" style="padding: 5%;">
      <h1 style="color: black;">Login</h1>
    </div>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group" style="color: black; font-weight: 600">
        {{ form.teamname.label(class="form-group") }}
        {{form.teamname(class='form-control') }}
      </div>
      <div class="form-group" style="color: black; font-weight: 600">
        {{ form.password.label(class="form-group") }}
        {{form.password(class='form-control') }}
      </div>
      <div class="form-group text-center">
        {{ form.submit( class="loginbtn") }}
      </div>
    </form>
  </div>
</div>
{% endblock %}

submiss/templates/notifications.html
{% extends "base.html" %} {% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    width: 100%;
  "
>
  <div class="container" style="min-height: 100vh;">
    {% for notif in notifs %}
    <div class="card bg-white" style="margin-top: 2%">
      <div class="card-body" style="color:black; padding">{{notif.message}}</div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

submiss/templates/register.html
{% extends "base.html" %} {% block content %}
<div
  style="
    background: radial-gradient(#edfda3d0 30%, #f0aa12e9 100%);
    width: 100%;
    min-height: 100vh;
    padding: 3%;
  "
>
  <div
    class="container"
    style="
      width: 450px;
      background: linear-gradient(
        #92a3f9 5%,

        rgba(201, 249, 166, 0.923) 100%
      );
      height: 120vh;
      box-shadow: 3px 3px 15px #181717;
      border-radius: 5px;
    "
  >
    <div class="text-center">
      <h1 style="color: black;">Register</h1>
    </div>
    <form method="POST">
      {{ form.hidden_tag() }}
      <div class="form-group" style="color: black; font-weight: 600;">
        {{ form.username.label(class="form-group") }}
        {{form.username(class='form-control') }}<br />
        {% for error in form.username.errors %}
        <span style="color: red">[{{ error }}]</span><br />
        {% endfor %}
      </div>

      <div class="form-group" style="color: black; font-weight: 600;">
        {{ form.roll.label(class="form-group") }}
        {{form.roll(class='form-control') }}<br />
        {% for error in form.roll.errors %}
        <span style="color: red">[{{ error }}]</span><br />
        {% endfor %}
      </div>

      <div class="form-group" style="color: black; font-weight: 600;">
        {{ form.roll2.label(class="form-group") }}
        {{form.roll2(class='form-control') }}<br />
        {% for error in form.roll2.errors %}
        <span style="color: red">[{{ error }}]</span><br />
        {% endfor %}
      </div>

      <div class="form-group" style="color: black; font-weight: 600;">
        {{ form.password.label(class="form-group") }}
        {{form.password(class='form-control') }}<br />
        {% for error in form.password.errors %}
        <span style="color: red">[{{ error }}]</span><br />
        {% endfor %}
      </div>
      <div class="form-group" style="color: black; font-weight: 600;">
        {{ form.pass_confirm.label(class="form-group") }}
        {{form.pass_confirm(class='form-control') }}<br />
      </div>
      <div class="form-group text-center">
        {{ form.submit(class="loginbtn") }}
      </div>
    </form>
  </div>
</div>

{% endblock %}

submiss/templates/submission.html
{% extends "base.html" %}
{% block content %}
<div class="subcontainer">
  <form method="POST" class="subform"  enctype="multipart/form-data">
    {{ form.hidden_tag() }} 
    <div class="form-group">
      {{ form.ans.label(class="form-group text-dark") }}
      {{form.ans(class='form-control bg-dark text-white')  }}<br>
      {% for error in form.ans.errors %}
        <span style="color: red;">[{{ error }}]</span><br>
      {% endfor %}
    </div>
    <div class="form-group">
      {{ form.picture.label(class="form-group text-dark") }}
      {{form.picture(class='bg-dark text-white')  }}<br>
      {% for error in form.picture.errors %}
        <span style="color: red;">[{{ error }}]</span><br>
      {% endfor %}
    </div>
    <div class="form-group text-center">
        {{ form.submit(class="btn btn-danger") }}
    </div>
  </form>
</div>

{% endblock %}